extends: ['airbnb', 'plugin:prettier/recommended']

env:
  node: true
  browser: true

parser: 'babel-eslint'

plugins:
  - jest
  - no-constructor-bind
  - eslint-plugin-local-rules

overrides:
  - files:
      - '*.spec.js'
    env:
      jest: true
    rules:
      no-unused-expressions: off
      func-names: off
    globals:
      sandbox: true
      flushPromises: true

rules:
  import/no-unresolved:
    - error
    - ignore:
        - '^~'
        - '^@'
  local-rules/acronyms:
    - warn
    - - 'API'
      - 'URI'
      - 'URN'
      - 'URL'
      - 'HTML'
      - 'RAML'
      - 'REST'
      - 'SOAP'
      - 'ANG'
  import/extensions:
    - error
    - js: never
      json: always
      svg: always
      css: always
      container: always
      resolver: always
  import/no-extraneous-dependencies:
    - off
  import/prefer-default-export:
    - off
  react/jsx-filename-extension:
    - off
  react/forbid-prop-types:
    - off
  react/require-default-props:
    - off
  react/no-array-index-key:
    - off
  react/jsx-one-expression-per-line:
    - off
  react/static-property-placement:
    - error
    - static public field
  react/no-access-state-in-setstate:
    - off
  react/destructuring-assignment:
    - off
  react/no-multi-comp:
    - off
  react/jsx-key:
    - error
  react/jsx-curly-newline:
    - off
  react/jsx-indent:
    - off
  react/jsx-props-no-spreading:
    - off
  react/state-in-constructor:
    - error
    - never
  react/jsx-wrap-multilines:
    - off
  react/jsx-fragments:
    - 2
    - element
  react/sort-comp:
    - error
    - order:
        - 'static-variables'
        - 'static-methods'
        - 'lifecycle'
        - 'everything-else'
        - 'render'

  no-constructor-bind/no-constructor-bind:
    - error
  no-constructor-bind/no-constructor-state:
    - error
  jsx-a11y/anchor-is-valid:
    - error
    - components:
        - 'Link'
      specialLink:
        - 'to'
  jsx-a11y/label-has-for: # deprecated in favor of jsx-a11y/label-has-associated-control but included by airbnb
    - off
  jsx-a11y/label-has-associated-control:
    - error
    - assert: 'either'
  # mocha/no-exclusive-tests:
  #   - error
  camelcase:
    - error
    - allow:
        - '^UNSAFE_'
      properties: 'never'
      ignoreDestructuring: false
      ignoreImports: false
  max-classes-per-file:
    - off
  no-use-before-define:
    - error
    - functions: false
  no-underscore-dangle:
    - error
    - allow:
        - '__INITIAL_STATE__'
        - '__RENDER_NAVBAR__'
        - '__PUBLIC_PATH__'
        - '__APHRODITE_RENDERED_CLASS_NAMES__'
  class-methods-use-this:
    - off
  padding-line-between-statements:
    - error
    - blankLine: always
      prev: '*'
      next: return
    - blankLine: always
      prev:
        - const
        - let
        - var
      next: '*'
    - blankLine: any
      prev:
        - const
        - let
        - var
      next:
        - const
        - let
        - var
  prefer-destructuring:
    - error
    - array: false
      object: true
  no-restricted-syntax:
    - off
  no-await-in-loop:
    - off
