extends: stylelint-config-standard

rules:
  selector-pseudo-class-no-unknown:
    [true, { ignorePseudoClasses: ['local', 'global'] }]
  selector-class-pattern: '^[a-z]([a-z0-9-]*)([a-z0-9])$'
  declaration-no-important: true
  no-duplicate-selectors: true
  at-rule-no-unknown: [true, { ignoreAtRules: ['define-mixin', 'mixin'] }]
  no-descending-specificity: null
  function-calc-no-invalid: null
